# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default=1, max_length=32, verbose_name='真是名称'),
            preserve_default=False,
        ),
    ]
