# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('crm', '0004_consultrecord_courserecord_paymentrecord_student_studyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='auth',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo', verbose_name='用户权限'),
        ),
    ]
